name = "stocksage-ai"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[[d1_databases]]
binding = "DB"
database_name = "stocksage-db"
database_id = "3b0199a4-a2c2-4476-baf3-f14e1cc6976a"
migrations_dir = "drizzle"
